### ISSUE TITLE
Fix double request on new rental

### ISSUE THREAD

**Issue by AdamVig** [emmanuelroussel/stockpile-app#188]
When starting a rental (typing a tag on the Scan screen and pressing Rent), during the transition from the Scan screen to the Rental Details screen, two identical `GET` requests are made for the added item.

Based on my simple debugging, one of them seems to come from `Rental.onAdd()` and the other from `Home.onNext()`.

**Comment by emmanuelroussel** [comment]
This is happening because the Home page needs to verify the item's status before pushing the Rental page, but it only passes the tag through nav params, so the Rental page has to get the item again to add it to the list (and to show brand and model). Changing the nav param to the whole item object will remove the unnecessary call.
